#!/bin/bash

#creador: Yisus7u7
#este programa es para reproducir musica con zenity y mpv

patch=$(zenity --file-selection --directory --title "enter the location of your directory with music" $HOME)

zenity --question --text "You want to play music on $patch?"

ans=$?
if [ $ans -eq 0 ]
then
    mpv -playlist $patch
else
    echo "Cancel"
    sleep 3 
    exit
    fi



